# ─── Screen ───
WIDTH = 700
HEIGHT = 400
FPS = 1000 #60

# ─── Colors ───
BROWN = (180, 130, 0)
BLACK = (0, 0, 0)
RED = (255, 0, 0)

# ─── Bird ───
BIRD_START_X = 45
BIRD_START_Y = 315
BIRD_SIZE = 30
BIRD_OUT_BOTTOM = 400
BIRD_OUT_RIGHT = 700

# ─── Physics ───
GRAVITY = 2
ACTION_COMPONENTS = 10          # each action axis: 0..9
NUM_ACTIONS = ACTION_COMPONENTS * ACTION_COMPONENTS  # 100
VX_SCALE = 2                    # vx = (action[0] + 1) * VX_SCALE
VY_SCALE = -5                   # vy = (action[1] - 1) * VY_SCALE

# ─── Ground / Floor ───
GROUND_Y = 360

# ─── Pig ───
PIG_SIZE = 40
PIG_FALL_MAX_Y = 1000

# ─── Block defaults ───
BLOCK_DEFAULT_WIDTH = 20
BLOCK_DEFAULT_HEIGHT = 60
BLOCK_INITIAL_ANGLE = 360
BLOCK_ROTATE_SPEED = 3
BLOCK_MAX_HITS = 2

# ─── Level generation ───
LEVEL_NUM_BUILDINGS = 2
LEVEL_BUILDING_X_MIN = 250
LEVEL_BUILDING_X_MAX = 600
LEVEL_HORIZONTAL_CHANCE = 0.3
LEVEL_HORIZONTAL_WIDTH = 60
LEVEL_HORIZONTAL_HEIGHT = 20

# ─── Rewards ───
REWARD_SHOOT = 0.1
REWARD_BLOCK_PIG_COLLIDE = 0.3
REWARD_PIG_KILL = 3.0
REWARD_ALL_PIGS_DEAD = 5.0
REWARD_MISS_PENALTY = -1.0
REWARD_LOSS_PENALTY = -5.0

# ─── Episode scoring for wandb (not used for training) ───
SCORE_BIRD_FIRED = -10
SCORE_PIG_KILLED = 25
SCORE_WIN = 50
SCORE_LOSS = -25

# ─── Stabilization ───
MAX_STEPS_SINCE_SHOT = 100
BLOCK_SNAP_TOLERANCE = 10

# ─── Game ───
INITIAL_TRIES = 10
INITIAL_LEVEL = 1

# ─── Rug image ───
RUG_SIZE = 60
RUG_X = 10
RUG_Y = 296

# ─── State ───
MAX_PIGS = 2
MAX_BLOCKS = 2
BLOCK_SIZE_NORM = 100.0
BLOCK_ANGLE_NORM = 360.0
BLOCK_HIT_NORM = 2.0

# ─── DQN network ───
DQN_LAYER1 = 128
DQN_LAYER2 = 128
GAMMA = 0.99

# ─── DQN agent ───
EPSILON_START = 1
EPSILON_FINAL = 0.01
EPSILON_DECAY = 200

# ─── Training ───
TRAIN_EPOCHS = 1000001
TARGET_UPDATE_INTERVAL = 50
TRAIN_BATCH_SIZE = 128
TRAIN_LR = 0.00001
GRAD_MAX_NORM = 1.0
WIN_THRESHOLD = 0.95
REPLAY_BUFFER_CAPACITY = 10000
DEFAULT_MODEL_PATH = "Data/DQN_PARAM_Advanced_7.pth"

# ─── Game Over display ───
GAME_OVER_FONT_SIZE = 60
GAME_OVER_WAIT_MS = 1500
